In [1]:
# Deep Learning model using LSTM

In [2]:
import numpy as np
import pandas as pd
import urllib
url = "https://goo.gl/uWbihf"
data = pd.read_csv (url, sep =";")
loc = "C:\\Users\\dell\\Desktop\\Rohan\\model\\Monthly Sunspots.csv"
data.to_csv(loc, index = False )
data_csv = pd.read_csv(loc, header = None )

In [76]:
yt=data_csv.iloc[0:3210 ,3]

In [77]:
print(yt.head())

0     96.7
1    104.3
2    116.7
3     92.8
4    141.7
Name: 3, dtype: float64


In [82]:
yt.tail()

3205    56.4
3206    54.1
3207    37.9
3208    51.5
3209    20.5
Name: 3, dtype: float64

In [5]:
!pip3 install statsmodels

In [15]:
from statsmodels.tsa.stattools import pacf


In [9]:
pacf(yt, nlags=40, method='ols')

array([ 1.00000000e+00,  9.16988688e-01,  2.73229024e-01,  1.91578477e-01,
        1.40770658e-01,  6.24773492e-02,  5.20282296e-02, -1.25139157e-02,
        1.84620043e-02,  3.63264636e-02, -4.82746402e-02, -5.37070742e-02,
       -6.56492408e-02, -7.71763257e-02, -4.53732514e-02, -6.19153840e-02,
       -9.77329104e-02, -6.60940870e-02, -9.45315606e-02, -3.90225063e-02,
       -5.19506186e-02, -5.88824378e-02, -3.86916023e-03, -6.82764163e-04,
       -5.65303236e-02,  3.79362879e-02, -3.31765360e-02, -6.49203717e-02,
       -2.94703923e-02, -3.03595527e-02,  1.72621989e-02, -3.01891181e-02,
        2.02131232e-02, -3.18439997e-02, -4.10513465e-02, -1.91054692e-02,
       -8.37831692e-03, -5.67418402e-03,  3.95280771e-03, -1.27290752e-02,
        2.38463992e-02])

In [16]:
# plot pacf and check correlation

In [18]:
yt_1 =yt.shift (1)
yt_2 =yt.shift (2)
yt_3 =yt.shift (3)
yt_4 =yt.shift (4)
yt_5 =yt.shift (5)

In [21]:
data =pd.concat ([yt ,yt_1 , yt_2 ,yt_3 ,yt_4 , yt_5 ], axis =1)
data.columns = ['yt', 'yt_1', 'yt_2','yt_3','yt_4','yt_5']

In [22]:
print(data.tail())

        yt  yt_1  yt_2  yt_3  yt_4  yt_5
3205  56.4  57.0  58.0  62.2  63.6  78.6
3206  54.1  56.4  57.0  58.0  62.2  63.6
3207  37.9  54.1  56.4  57.0  58.0  62.2
3208  51.5  37.9  54.1  56.4  57.0  58.0
3209  20.5  51.5  37.9  54.1  56.4  57.0


In [23]:
print(data.head())

      yt   yt_1   yt_2   yt_3  yt_4  yt_5
0   96.7    NaN    NaN    NaN   NaN   NaN
1  104.3   96.7    NaN    NaN   NaN   NaN
2  116.7  104.3   96.7    NaN   NaN   NaN
3   92.8  116.7  104.3   96.7   NaN   NaN
4  141.7   92.8  116.7  104.3  96.7   NaN


In [24]:
data = data.dropna()

In [25]:
y = data['yt']

In [26]:
cols = ['yt_1', 'yt_2', 'yt_3', 'yt_4', 'yt_5']

In [27]:
x = data[cols]

In [28]:
print(y.tail())

3205    56.4
3206    54.1
3207    37.9
3208    51.5
3209    20.5
Name: yt, dtype: float64


In [29]:
print(y.head())

5    139.2
6    158.0
7    110.5
8    126.5
9    125.8
Name: yt, dtype: float64


In [30]:
print(x.head())

    yt_1   yt_2   yt_3   yt_4   yt_5
5  141.7   92.8  116.7  104.3   96.7
6  139.2  141.7   92.8  116.7  104.3
7  158.0  139.2  141.7   92.8  116.7
8  110.5  158.0  139.2  141.7   92.8
9  126.5  110.5  158.0  139.2  141.7


In [31]:
print(x.tail())

      yt_1  yt_2  yt_3  yt_4  yt_5
3205  57.0  58.0  62.2  63.6  78.6
3206  56.4  57.0  58.0  62.2  63.6
3207  54.1  56.4  57.0  58.0  62.2
3208  37.9  54.1  56.4  57.0  58.0
3209  51.5  37.9  54.1  56.4  57.0


In [32]:
from sklearn import preprocessing

In [39]:
scaler_x = preprocessing.MinMaxScaler(feature_range=(-1, 1))

In [40]:
x = np.array(x).reshape((len(x), 5))

In [41]:
x

array([[141.7,  92.8, 116.7, 104.3,  96.7],
       [139.2, 141.7,  92.8, 116.7, 104.3],
       [158. , 139.2, 141.7,  92.8, 116.7],
       ...,
       [ 54.1,  56.4,  57. ,  58. ,  62.2],
       [ 37.9,  54.1,  56.4,  57. ,  58. ],
       [ 51.5,  37.9,  54.1,  56.4,  57. ]])

In [42]:
x = scaler_x.fit_transform(x)

In [43]:
x

array([[-0.28829734, -0.53390256, -0.41386238, -0.47614264, -0.51431441],
       [-0.30085384, -0.28829734, -0.53390256, -0.41386238, -0.47614264],
       [-0.20642893, -0.30085384, -0.28829734, -0.53390256, -0.41386238],
       ...,
       [-0.72827725, -0.71672526, -0.7137117 , -0.7086891 , -0.68759417],
       [-0.8096434 , -0.72827725, -0.71672526, -0.7137117 , -0.7086891 ],
       [-0.74133601, -0.8096434 , -0.72827725, -0.71672526, -0.7137117 ]])

In [44]:
scaler_y = preprocessing.MinMaxScaler(feature_range=(-1,1))

In [45]:
y = np.array(y).reshape((len(y), 1))

In [46]:
y = scaler_y.fit_transform(y)

In [47]:
y

array([[-0.30085384],
       [-0.20642893],
       [-0.44500251],
       ...,
       [-0.8096434 ],
       [-0.74133601],
       [-0.89703666]])

In [48]:
train_end = 3042

In [49]:
x_train = x[0:train_end,]

In [51]:
x_test = x[train_end+1:3205,]

In [52]:
y_train = y[0:train_end,]

In [53]:
y_test = y[train_end+1: 3205]

In [57]:
x_train.shape

(3042, 5)

In [58]:
x_test.shape


(162, 5)

In [59]:
y_train.shape


(3042, 1)

In [60]:
y_test.shape

(162, 1)

In [61]:
x_train = x_train.reshape(x_train.shape + (1,))

In [62]:
x_test = x_test.reshape(x_test.shape + (1,))

In [63]:
print(x_train.shape)

(3042, 5, 1)


In [65]:
# !pip3 install tensorflow
# !pip3 install keras

^C


In [ ]:
from keras.models import Sequential

from keras.layers.core import Dense, Activation
from keras.layers.recurrent import LSTM
seed =2016
np.random.seed(seed)
fit1 = Sequential()
fit1.add(LSTM(output_dim =4, activation ='tanh', inner_activation ='hard_sigmoid', 
              input_shape =(5 , 1)))
fit1.add(Dense(output_dim=1, activation ='linear'))

In [67]:
fit1.compile(loss ="mean_squared_error", 
             optimizer ="rmsprop")

In [83]:
fit1.fit(x_train, y_train, batch_size=1, 
          epochs =10 , shuffle = True )

Epoch 1/10
   8/3042 [..............................] - ETA: 1:07 - loss: 0.0252

C:\Users\dell\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  


3042/3042 [==============================] - 21s 7ms/step - loss: 0.0195
Epoch 2/10
3042/3042 [==============================] - 15s 5ms/step - loss: 0.0189
Epoch 3/10
3042/3042 [==============================] - 15s 5ms/step - loss: 0.0186
Epoch 4/10
3042/3042 [==============================] - 16s 5ms/step - loss: 0.0184
Epoch 5/10
3042/3042 [==============================] - 16s 5ms/step - loss: 0.0183
Epoch 6/10
3042/3042 [==============================] - 17s 6ms/step - loss: 0.0182
Epoch 7/10
3042/3042 [==============================] - 17s 5ms/step - loss: 0.0181
Epoch 8/10
3042/3042 [==============================] - 16s 5ms/step - loss: 0.0181
Epoch 9/10
3042/3042 [==============================] - 15s 5ms/step - loss: 0.0180
Epoch 10/10
3042/3042 [==============================] - 15s 5ms/step - loss: 0.0180


In [84]:
score_train = fit1.evaluate(x_train , y_train , batch_size =1)
score_test = fit1.evaluate(x_test , y_test , batch_size =1)

162/162 [==============================] - 1s 3ms/step


In [85]:
print("in train MSE = ", round( score_train , 4))

in train MSE =  0.0175


In [86]:
print("in test MSE = ", round( score_test ,4))

in test MSE =  0.0076


In [87]:
pred1 = fit1.predict(x_test)
pred1 = scaler_y.inverse_transform(np.array(pred1).reshape((len(pred1), 1)))

y_act = scaler_y.inverse_transform(np.array(y_test))

In [88]:
pred1


array([[141.94547  ],
       [133.63435  ],
       [106.47105  ],
       [ 99.49546  ],
       [ 95.06303  ],
       [ 88.17561  ],
       [ 99.93991  ],
       [110.48217  ],
       [112.25101  ],
       [ 98.21011  ],
       [ 95.11684  ],
       [ 86.778496 ],
       [ 77.61045  ],
       [ 68.94947  ],
       [ 68.29147  ],
       [ 68.96855  ],
       [ 63.54905  ],
       [ 66.25026  ],
       [ 64.94229  ],
       [ 71.11228  ],
       [ 70.22696  ],
       [ 59.938618 ],
       [ 64.01415  ],
       [ 64.58319  ],
       [ 47.930634 ],
       [ 46.331707 ],
       [ 42.809734 ],
       [ 38.596943 ],
       [ 37.742596 ],
       [ 46.281605 ],
       [ 50.12504  ],
       [ 54.951912 ],
       [ 57.279278 ],
       [ 47.61145  ],
       [ 31.353224 ],
       [ 26.634174 ],
       [ 36.93218  ],
       [ 29.211298 ],
       [ 19.083662 ],
       [ 17.075527 ],
       [ 27.379179 ],
       [ 31.131638 ],
       [ 28.804487 ],
       [ 25.658659 ],
       [ 21.405472 ],
       [ 2